import { useState } from "react";
import "./StakeholderAdvisory.css";

function StakeholderAdvisory({ region }) {
  const [selectedStakeholder, setSelectedStakeholder] =
    useState("citizen");

  if (!region) {
    return null;
  }

  const temperature =
    Number(region.temperature) || 0;

  const departure =
    Number(region.departure) || 0;

  const humidity =
    Number(region.humidity) || 0;

  const minTemperature =
    Number(region.minTemp) || 0;

  const severity =
    region.severity || "Moderate";

  const risk =
    region.risk || "Moderate";


  /*
   * =====================================================
   * STAKEHOLDER ADVISORY GENERATION
   * =====================================================
   *
   * These are prototype rule-based advisories.
   *
   * Later, these can be generated by the backend /
   * AI model using the actual forecast and risk output.
   */


  const advisoryData = {

    citizen: {

      label: "Citizen",

      icon: "👤",

      title:
        "Public Heat Safety Advisory",

      priority:
        severity.toLowerCase() === "severe"
          ? "URGENT"
          : severity.toLowerCase() === "high"
          ? "HIGH PRIORITY"
          : "ADVISORY",

      summary:
        `Heat conditions in ${region.name} require residents to take precautions against prolonged heat exposure.`,

      actions: [

        "Avoid prolonged outdoor activity during the hottest part of the day.",

        "Drink water regularly and stay hydrated even when you do not feel thirsty.",

        "Use shaded or air-conditioned spaces whenever possible.",

        "Wear lightweight, loose-fitting clothing when outdoors.",

        "Check on elderly people, children and others who may be more vulnerable to heat."

      ],

      metrics: [

        {
          label: "Temperature",
          value: `${temperature}°C`,
        },

        {
          label: "Above normal",
          value: `+${departure}°C`,
        },

        {
          label: "Humidity",
          value: `${humidity}%`,
        },

      ],

    },


    farmer: {

      label: "Farmer",

      icon: "🌾",

      title:
        "Agricultural Heat Advisory",

      priority:
        temperature >= 44
          ? "URGENT"
          : temperature >= 40
          ? "HIGH PRIORITY"
          : "ADVISORY",

      summary:
        `Elevated temperatures in ${region.name} may increase heat stress for crops, livestock and agricultural workers.`,

      actions: [

        "Schedule physically demanding field activities during early morning or evening hours.",

        "Maintain adequate irrigation and monitor soil moisture during prolonged hot conditions.",

        "Provide sufficient drinking water and shaded areas for livestock.",

        "Monitor crops for signs of heat stress, wilting or moisture loss.",

        "Avoid unnecessary exposure of agricultural workers during peak afternoon heat."

      ],

      metrics: [

        {
          label: "Temperature",
          value: `${temperature}°C`,
        },

        {
          label: "Minimum",
          value: `${minTemperature}°C`,
        },

        {
          label: "Departure",
          value: `+${departure}°C`,
        },

      ],

    },


    health: {

      label: "Health Department",

      icon: "🏥",

      title:
        "Public Health Heat Advisory",

      priority:
        severity.toLowerCase() === "severe"
          ? "URGENT"
          : severity.toLowerCase() === "high"
          ? "HIGH PRIORITY"
          : "ADVISORY",

      summary:
        `Current heat indicators in ${region.name} suggest increased potential for heat-related illness and healthcare demand.`,

      actions: [

        "Prepare healthcare facilities for a potential increase in heat-related illness cases.",

        "Increase public communication about hydration, heat exposure and warning signs.",

        "Pay particular attention to elderly people, children and individuals with heat-sensitive conditions.",

        "Monitor emergency department and ambulance demand during periods of extreme heat.",

        "Coordinate with local authorities if heatwave conditions intensify."

      ],

      metrics: [

        {
          label: "Risk",
          value: risk,
        },

        {
          label: "Severity",
          value: severity,
        },

        {
          label: "Temperature",
          value: `${temperature}°C`,
        },

      ],

    },


    authority: {

      label: "Local Authority",

      icon: "🚨",

      title:
        "Heat Action Advisory",

      priority:
        severity.toLowerCase() === "severe"
          ? "IMMEDIATE ACTION"
          : severity.toLowerCase() === "high"
          ? "HIGH PRIORITY"
          : "MONITOR",

      summary:
        `Regional conditions in ${region.name} should be monitored for potential escalation of heatwave response measures.`,

      actions: [

        "Review current heat action plans and confirm readiness of response teams.",

        "Monitor vulnerable locations and communities for increasing heat exposure.",

        "Coordinate public warnings through appropriate communication channels.",

        "Prepare cooling centres and emergency resources if conditions worsen.",

        "Coordinate with health, disaster-management and municipal teams for escalation."

      ],

      metrics: [

        {
          label: "Risk",
          value: risk,
        },

        {
          label: "Severity",
          value: severity,
        },

        {
          label: "Departure",
          value: `+${departure}°C`,
        },

      ],

    },

  };


  const advisory =
    advisoryData[selectedStakeholder];


  return (
    <section className="panel stakeholder-advisory-card">


      {/* =====================================================
          HEADER
      ====================================================== */}

      <div className="stakeholder-header">

        <div>

          <div className="micro-label">
            DECISION SUPPORT
          </div>

          <h3>
            Stakeholder-Specific Advisory
          </h3>

          <p>
            Recommended actions based on the current
            heat conditions in {region.name}.
          </p>

        </div>


        <div className="stakeholder-region">

          {region.name}

        </div>

      </div>


      {/* =====================================================
          STAKEHOLDER SELECTOR
      ====================================================== */}

      <div className="stakeholder-tabs">

        {Object.entries(advisoryData).map(
          ([key, item]) => (

            <button
              key={key}
              type="button"
              className={
                selectedStakeholder === key
                  ? "stakeholder-tab active"
                  : "stakeholder-tab"
              }
              onClick={() =>
                setSelectedStakeholder(key)
              }
            >

              <span className="stakeholder-icon">
                {item.icon}
              </span>

              <span>
                {item.label}
              </span>

            </button>

          )
        )}

      </div>


      {/* =====================================================
          ADVISORY CONTENT
      ====================================================== */}

      <div className="stakeholder-advisory-content">


        {/* TITLE */}

        <div className="stakeholder-advisory-heading">

          <div>

            <span className="stakeholder-type">

              {advisory.icon}

              {advisory.label}

            </span>

            <h4>
              {advisory.title}
            </h4>

          </div>


          <span
            className={`
              advisory-priority
              ${
                advisory.priority ===
                "IMMEDIATE ACTION"
                  ? "urgent"
                  : advisory.priority ===
                    "URGENT"
                  ? "urgent"
                  : advisory.priority ===
                    "HIGH PRIORITY"
                  ? "high"
                  : "normal"
              }
            `}
          >
            {advisory.priority}
          </span>

        </div>


        {/* SUMMARY */}

        <p className="stakeholder-summary">
          {advisory.summary}
        </p>


        {/* ACTIONS */}

        <div className="stakeholder-actions">

          <div className="actions-heading">

            <span>
              RECOMMENDED ACTIONS
            </span>

          </div>


          {advisory.actions.map(
            (action, index) => (

              <div
                className="stakeholder-action"
                key={index}
              >

                <span className="action-number">
                  {String(index + 1).padStart(
                    2,
                    "0"
                  )}
                </span>

                <p>
                  {action}
                </p>

              </div>

            )
          )}

        </div>


        {/* CURRENT CONDITIONS */}

        <div className="stakeholder-metrics">

          {advisory.metrics.map(
            (metric) => (

              <div
                key={metric.label}
                className="stakeholder-metric"
              >

                <span>
                  {metric.label}
                </span>

                <strong>
                  {metric.value}
                </strong>

              </div>

            )
          )}

        </div>


        {/* FOOTNOTE */}

        <div className="stakeholder-note">

          Advisory generated from current regional
          heat indicators. Final operational guidance
          should be based on official warnings and
          validated forecast information.

        </div>

      </div>

    </section>
  );
}

export default StakeholderAdvisory;